package com.mdmobile.cyclops.dataModel.api.devices.test.dev

import com.google.gson.annotations.SerializedName
import com.mdmobile.cyclops.dataModel.api.devices.test.DeviceUserInfo
import com.mdmobile.cyclops.dataModel.api.devices.test.Memory

class iOS(
        @SerializedName("AgentVersion") val agentVersion: Any = Any(),
        @SerializedName("Memory") val memory: Memory = Memory(),
        @SerializedName("BatteryStatus") val batteryStatus: Int = 0,
        @SerializedName("BluetoothMACAddress") val bluetoothMACAddress: String = "",
        @SerializedName("BuildVersion") val buildVersion: String = "",
        @SerializedName("CarrierSettingsVersion") val carrierSettingsVersion: String = "",
        @SerializedName("CellularCarrier") val cellularCarrier: String = "",
        @SerializedName("CellularTechnology") val cellularTechnology: String = "",
        @SerializedName("CurrentMCC") val currentMCC: String = "",
        @SerializedName("CurrentMNC") val currentMNC: String = "",
        @SerializedName("DataRoamingEnabled") val dataRoamingEnabled: Boolean = false,
        @SerializedName("DeviceTerms") val deviceTerms: Any = Any(),
        @SerializedName("DeviceUserInfo") val deviceUserInfo: DeviceUserInfo = DeviceUserInfo(),
        @SerializedName("ExchangeBlocked") val exchangeBlocked: Boolean = false,
        @SerializedName("ExchangeStatus") val exchangeStatus: String = "",
        @SerializedName("FirmwareVersion") val firmwareVersion: Any = Any(),
        @SerializedName("HardwareEncryptionCaps") val hardwareEncryptionCaps: Int = 0,
        @SerializedName("ICCID") val iCCID: String = "",
        @SerializedName("IMEI_MEID_ESN") val iMEIMEIDESN: String = "",
        @SerializedName("InRoaming") val inRoaming: Boolean = false,
        @SerializedName("Ipv6") val ipv6: Any = Any(),
        @SerializedName("IsAgentCompatible") val isAgentCompatible: Boolean = false,
        @SerializedName("IsAgentless") val isAgentless: Boolean = false,
        @SerializedName("IsDeviceLocatorServiceEnabled") val isDeviceLocatorServiceEnabled: Any = Any(),
        @SerializedName("IsDoNotDisturbInEffect") val isDoNotDisturbInEffect: Any = Any(),
        @SerializedName("IsEncrypted") val isEncrypted: Boolean = false,
        @SerializedName("IsEnrolled") val isEnrolled: Boolean = false,
        @SerializedName("IsITunesStoreAccountActive") val isITunesStoreAccountActive: Any = Any(),
        @SerializedName("IsOSSecure") val isOSSecure: Boolean = false,
        @SerializedName("IsPersonalHotspotEnabled") val isPersonalHotspotEnabled: Any = Any(),
        @SerializedName("IsSupervised") val isSupervised: Boolean = false,
        @SerializedName("LastCheckInTime") val lastCheckInTime: Any = Any(),
        @SerializedName("LastAgentConnectTime") val lastAgentConnectTime: Any = Any(),
        @SerializedName("LastAgentDisconnectTime") val lastAgentDisconnectTime: Any = Any(),
        @SerializedName("LastLoggedOnUser") val lastLoggedOnUser: Any = Any(),
        @SerializedName("LastStatusUpdate") val lastStatusUpdate: String = "",
        @SerializedName("ManufacturerSerialNumber") val manufacturerSerialNumber: String = "",
        @SerializedName("ModelNumber") val modelNumber: String = "",
        @SerializedName("ModemFirmwareVersion") val modemFirmwareVersion: String = "",
        @SerializedName("NetworkConnectionType") val networkConnectionType: Any = Any(),
        @SerializedName("PasscodeEnabled") val passcodeEnabled: Boolean = false,
        @SerializedName("PasscodeStatus") val passcodeStatus: String = "",
        @SerializedName("PersonalizedName") val personalizedName: String = "",
        @SerializedName("PhoneNumber") val phoneNumber: String = "",
        @SerializedName("ProductName") val productName: String = "",
        @SerializedName("SIMCarrierNetwork") val sIMCarrierNetwork: String = "",
        @SerializedName("SubscriberMCC") val subscriberMCC: Any = Any(),
        @SerializedName("SubscriberMNC") val subscriberMNC: String = "",
        @SerializedName("SubscriberNumber") val subscriberNumber: Any = Any(),
        @SerializedName("UserIdHash") val userIdHash: Any = Any(),
        @SerializedName("VoiceRoamingEnabled") val voiceRoamingEnabled: Boolean = false,
        kind: String, complianceStatus: Boolean, complianceItems: List<ComplianceItem>, deviceId: String,
        deviceName: String, enrollmentTime: String, family: String, hostName: String, isAgentOnline: Boolean, isVirtual: Boolean,
        customAttributes: List<CustomAttribute>, mACAddress: String, manufacturer: String, mode: String, model: String, oSVersion: String,
        path: String, platform: String)
    : BasicDevice(kind, complianceStatus, complianceItems, deviceId, deviceName, enrollmentTime, family, hostName,
        isAgentOnline, isVirtual,customAttributes,mACAddress, manufacturer, mode, model, oSVersion, path, platform)